In [1]:
import numpy as np
import pandas as pd

**creating numpy array**

In [5]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [6]:
np.array([1,2,3,4],dtype=np.float32)

array([1., 2., 3., 4.], dtype=float32)

In [7]:
np.array([1,2.0,3,4])

array([1., 2., 3., 4.])

**multi-dimensional arrays**

In [8]:
np.array([[1,2,3,4],[5,6,7,8]])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

**array of zeros**

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

**array of ones**

In [11]:
np.ones(5,dtype=np.int32)

array([1, 1, 1, 1, 1])

**Random numbers**

In [13]:
np.random.rand(2,3)

array([[0.59618866, 0.79342472, 0.58216361],
       [0.90209874, 0.78751365, 0.29315496]])

**To create an array filled with any given value using the np.full() method**

In [14]:
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

**Identity matrix**

In [15]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**Evenly spaced array**

In [16]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [17]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [18]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

**dimension of numpy arrays**

In [19]:
a=np.array([[5,10,15],[20,25,20]])
print('Array : ','\n',a)
print('Dimensions : ','\n',a.ndim)

Array :  
 [[ 5 10 15]
 [20 25 20]]
Dimensions :  
 2


**shape of numpy array**

In [20]:
a = np.array([[1,2,3],[4,5,6]])
print('Array :','\n',a)
print('Shape :','\n',a.shape)
print('Rows = ',a.shape[0])
print('Columns = ',a.shape[1])

Array : 
 [[1 2 3]
 [4 5 6]]
Shape : 
 (2, 3)
Rows =  2
Columns =  3


**size of numpy array**

In [21]:
a = np.array([[5,10,15],[20,25,20]])
print('Size of array :',a.size)
print('Manual determination of size of array :',a.shape[0]*a.shape[1])

Size of array : 6
Manual determination of size of array : 6


**reshaping of numpy array**

In [22]:
a = np.array([3,6,9,12])
np.reshape(a,(2,2))

array([[ 3,  6],
       [ 9, 12]])

In [23]:
a = np.array([3,6,9,12,18,24])
print('Three rows :','\n',np.reshape(a,(3,-1)))
print('Three columns :','\n',np.reshape(a,(-1,3)))

Three rows : 
 [[ 3  6]
 [ 9 12]
 [18 24]]
Three columns : 
 [[ 3  6  9]
 [12 18 24]]


**flattening a numpy array**

In [24]:
a = np.ones((2,2))
b = a.flatten()
c = a.ravel()
print('Original shape :', a.shape)
print('Array :','\n', a)
print('Shape after flatten :',b.shape)
print('Array :','\n', b)
print('Shape after ravel :',c.shape)
print('Array :','\n', c)

Original shape : (2, 2)
Array : 
 [[1. 1.]
 [1. 1.]]
Shape after flatten : (4,)
Array : 
 [1. 1. 1. 1.]
Shape after ravel : (4,)
Array : 
 [1. 1. 1. 1.]


**transpose of an array**

In [25]:
a = np.array([[1,2,3],
[4,5,6]])
b = np.transpose(a)
print('Original','\n','Shape',a.shape,'\n',a)
print('Expand along columns:','\n','Shape',b.shape,'\n',b)

Original 
 Shape (2, 3) 
 [[1 2 3]
 [4 5 6]]
Expand along columns: 
 Shape (3, 2) 
 [[1 4]
 [2 5]
 [3 6]]


**sort the elements in the array**

In [26]:
np.sort([56,34,78,89,23])

array([23, 34, 56, 78, 89])

**mean**

In [27]:
arr=[34,23,6,78,45,12,36]
np.mean(arr)

33.42857142857143

**median**

In [28]:
np.median(arr)

34.0

**Mode**

In [29]:
from scipy import stats
stats.mode(arr)

ModeResult(mode=array([6]), count=array([1]))

**standard deviation**

In [31]:
np.std(arr)

22.19303071337707

**where()**

In [37]:
arr=np.array([0,1,4,3,8,5,12,7,16,9,20])
x=np.where(arr%4==0)
print(x)
y=np.where(arr%3==0)
print(y)

(array([ 0,  2,  4,  6,  8, 10], dtype=int64),)
(array([0, 3, 6, 9], dtype=int64),)
